server:
  servlet:
    context-path: /credito
  port: ${CREDITO_PORT:8082}

spring:
  application:
    name: credito
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:financial_db}
    username: ${POSTGRES_USER:postgres_admin}
    password: ${POSTGRES_PASSWORD:postgres_secure_pass}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8080/realms/financeiro

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/

application:
  financeiro:
    url: http://${FINANCEIRO_HOST:localhost}:8083/financeiro